{% set version = '0.9-1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-qvcalc
  version: {{ version|replace("-", "_") }}

source:
  fn: qvcalc_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/qvcalc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/qvcalc/qvcalc_{{ version }}.tar.gz
  sha256: de2311ade76dae311b2b5632633003667aa46cdb8703a330b84b67c4b90f87d2

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1001
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('qvcalc')"           # [not win]
    - "\"%R%\" -e \"library('qvcalc')\""  # [win]

about:
  home: https://github.com/DavidFirth/qvcalc
  license: GPL-2 | GPL-3
  summary: Functions to compute quasi variances and associated measures of approximation error.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
