travis:
  secure:
    BINSTAR_TOKEN: ByoSS4JOhcerA2a5XtO4pOOlPpOa3TwbruXgH6F57uZi9FQbBz5HD1Zp60YjzikDjq/nJqustsbhPWRuRcF8riNc+mAucUqUnAFuh4zHbPy4LKR3sxucruprh0NWV2+u1nTK9zzF9tlcmlwcccM6Rq5bOsP6h3BxajhPG7Bv9hdYLNyAurWtN6Cb6C0FRfOzm6CMM5yQWktXO++ZOpgTmQGkr7uz53TKBhfYrrdmJjOsxLVRejPqa6JFBDmuejG6qU5QarWhMdHsLdZXEOrH2h/zCGFDmiBFRW7ZLconx5a9JWWBG5N9DLY5m6Q7f8tdJo0UMXMvUONFMV9MhuBUO2QI116X31UM0IZMSZpe7H+h/mk58I/WdOA4B1tEbWakKAj4GxqiwdZjsnFEqSAVeM6T71dh4QaOmV0du0jqJnu9n2jLLUVqvc4drVPajoMGKA3XmcFFdgK48003CbPGmliGc/402Qss+zd8VsJiuopmtJzbTgKcbuUyyvMqM4G5hVVL5Eeup1ggCoFHve0yZVSjshrTfQwUtrKaOz68rhxRx4ynlS7totXFa/xzDhqAqugUamgJteyUxwK6AY/bS3WogoKajnO0ieTZO3iiu1tI8edhFe6MhvDjhvJzDgHkofSziW5RTnKzZ3qnIJsD6EarUNdZdrpSuh6k4BRYRGU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
